steps:
  - name: "gcr.io/cloud-builders/mvn"
    args:
    - package
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tommie:$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/tommie:latest', '-f', 'Dockerfile2',  '.' ]  
images:
- 'gcr.io/$PROJECT_ID/tommie'   
