steps:
  
  - name: 'ubuntu'
    args: ['bash', './myscript.sh']
    env:
    - 'BUILD=$BUILD_ID'
    - 'PROJECT=$PROJECT_ID'
    - 'REV=$REVISION_ID'
  
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image', '.']
  
 
images:
  - 'gcr.io/$PROJECT_ID/my-image'
  