name: CIback

on:
 push:
   tags:
    v[0-9].[0-9]b


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: GitHub Action for Maven
      uses: comchangs/action-maven@v0.4-beta
      with:
       args: clean install
    
    - name: set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
  
      
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bugoga/tomat
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile2
        tags: ${{ env.RELEASE_VERSION }},latest
   
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az container restart --resource-group containers --name example-continst
             

