name: CIfront

on:
 push:
   tags:
    v[0-9].[0-9]f


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    
    - name: tele notification 1
      run: curl -s -X POST  https://api.telegram.org/bot${{ secrets.TELE_TOCKEN }}/sendMessage -d chat_id="${{ secrets.CHAT_ID }}" -d text="Build ${GITHUB_REF:10} started"

    - name: base64-to-full
      id: write_fullchain
      uses: timheuer/base64-to-file@v1.0.3
      with:
       fileName: 'fullchain.pem'
       encodedString: ${{ secrets.FULLCHAIN }}
    
    - name: base64-to-priv
      id: write_privkey
      uses: timheuer/base64-to-file@v1.0.3
      with:
       fileName: 'privkey.pem'
       encodedString: ${{ secrets.PRIVKEY }}
    
    - name: copy fullchain
      run: mv ${{ steps.write_fullchain.outputs.filePath }} ./conf
    
    - name: copy privkey
      run: mv ${{ steps.write_privkey.outputs.filePath }} ./conf
    
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bugoga/noginsk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tags: ${{ env.RELEASE_VERSION }},latest

    - name: tele notification 2
      run: curl -s -X POST  https://api.telegram.org/bot${{ secrets.TELE_TOCKEN }}/sendMessage -d chat_id="${{ secrets.CHAT_ID }}" -d text="Build ${GITHUB_REF:10} done"

    - name: tele notification 3
      run: curl -s -X POST  https://api.telegram.org/bot${{ secrets.TELE_TOCKEN }}/sendMessage -d chat_id="${{ secrets.CHAT_ID }}" -d text="Deploy ${GITHUB_REF:10} started"




   
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az container restart --resource-group containers --name example-continst
             
    - name: tele notification 4
      run: curl -s -X POST  https://api.telegram.org/bot${{ secrets.TELE_TOCKEN }}/sendMessage -d chat_id="${{ secrets.CHAT_ID }}" -d text="Deploy ${GITHUB_REF:10} done"
