name: CIback

on:
 push:
   tags:
    v[0-9].[0-9]f


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
  
      
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: bugoga/noginsk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile3
        tags: ${{ env.RELEASE_VERSION }},latest
   
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az container restart --resource-group containers --name example-continst
             
