name: SecretPiping

on:
  push:
    branches: 
      - testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: base64-to-file
      id: write_fullchain
      uses: timheuer/base64-to-file@v1.0.3
      with:
       fileName: 'fullchain.pem'
       encodedString: ${{ secrets.FULLCHAIN }}
    - name: base64-to-file
      id: write_privkey
      uses: timheuer/base64-to-file@v1.0.3
      with:
       fileName: 'privkey.pem'
       encodedString: ${{ secrets.PRIVKEY }}   

    - name: cat file
      run: cat ${{ steps.write_privkey.outputs.filePath }}
    
    - name: pwd
      run: pwd
      

