name: SecretPiping

on:
  push:
    branches: 
      - testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: base64-to-file
      id: write_file
      uses: timheuer/base64-to-file@v1.0.3
      with:
       fileName: 'fullchain.pem'
       encodedString: ${{ secrets.FULLCHAIN }}
    - name: cat file
      run: cat fullchain.pem
