name: SecretPiping

on:
  push:
    branches: 
      - testing

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decode fullchain
      run: echo ${{ secrets.FULLCHAIN }} | base64 -d  > fullchain.pem
    - name: Out fullchain
      run: cat fullchain.pem
